name: Build Apks

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'

jobs:
  build:
    name: Build Portal
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Setup Java 21
        uses:  gmitch215/setup-java@6d2c5e1f82f180ae79f799f0ed6e3e5efb4e664d
        with:
          distribution: jetbrains
          java-version: 21
          
      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-core-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: gradle-deps

      - name: Cache Gradle Build
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches/build-cache-*
            ~/.gradle/buildOutputCleanup/cache.properties
          key: gradle-builds-core-${{ github.sha }}
          restore-keys: gradle-builds

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew :app:assembleAppDebug --build-cache --parallel --warning-mode all --stacktrace
          echo "APK_FILE=$(find app/build/outputs/apk/app/debug -name '*.apk')" >> $GITHUB_ENV

      - name: Set Portal Version
        run: |
          version_name=$(basename -s .apk "${{ env.APK_FILE }}")
          echo "PORTAL_VERSION=$version_name" >> $GITHUB_ENV

      - name: Show Artifacts SHA256
        run: |
          echo "### Build Success :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "|ABI|SHA256|" >> $GITHUB_STEP_SUMMARY
          echo "|:--------:|:----------|" >> $GITHUB_STEP_SUMMARY
          apk=($(sha256sum "${{ env.APK_FILE }}"))
          echo "|all|$apk" >> $GITHUB_STEP_SUMMARY

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.PORTAL_VERSION }}"
          path: "${{ env.APK_FILE }}"
